---
- name: make sure monitor_interface, monitor_address or monitor_address_block is defined
  fail:
    msg: "you must set monitor_interface, monitor_address or monitor_address_block"
  when:
    - mon_group_name in group_names
    - monitor_interface == 'interface'
    - monitor_address == "x.x.x.x"
    - monitor_address_block == 'subnet'

- name: make sure radosgw_interface, radosgw_address or radosgw_address_block is defined
  fail:
    msg: "you must set radosgw_interface, radosgw_address or radosgw_address_block"
  when:
    - rgw_group_name in group_names
    - radosgw_interface == 'interface'
    - radosgw_address == 'x.x.x.x'
    - radosgw_address_block == 'subnet'
