---
- name: make sure /tmp exists
  file:
    path: /tmp
    state: directory
  when:
    - use_installer

- name: use mktemp to create name for rundep
  command: "mktemp /tmp/rundep.XXXXXXXX"
  register: rundep_location
  when:
    - use_installer

- name: copy rundep
  copy:
    src: "{{ansible_dir}}/rundep"
    dest: "{{ item }}"
  with_items: "{{ (rundep_location|default({})).stdout_lines|default([]) }}"
  when:
    - use_installer

- name: install ceph dependencies
  script: "{{ ansible_dir }}/rundep_installer.sh {{ item }}"
  become: true
  with_items: "{{ (rundep_location|default({})).stdout_lines|default([]) }}"
  when:
    - use_installer

#muhongtao@sensetime.com add 2020-09-03 
- name: check for ceph
  stat:
    path: /usr/bin/ceph
  ignore_errors: yes
  register: ceph_stat

- name: muhongtao print ceph_stat
  debug:
    msg: "muhongtao print ceph_stat: {{ ceph_stat }}"

- name: copy ceph package  
  copy:
    src: sense-ceph
    dest: /tmp/
  when:
    - ceph_stat.stat.exists == false

- name: install ceph
  shell: sh install 1> /tmp/sense-ceph.log 2>&1
  args:
    chdir: /tmp/sense-ceph/
  ignore_errors: yes
  when:
    - ceph_stat.stat.exists == false

- name: complete install ceph
  file:
    path: /tmp/sense-ceph/
    state: absent
  ignore_errors: yes
  when:
    - ceph_stat.stat.exists == false

- name: Firewall configuration
  service:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: yes
  when:
    - ceph_stat.stat.exists == false
#end add

#muhongtao@sensetime.com remove this part
#---------------------------------------
#- name: ensure rsync is installed
#  package:
#    name: rsync
#    state: present

#- name: synchronize ceph install
#  synchronize:
#    src: "{{ceph_installation_dir}}/"
#    dest: "/"

#- name: create user group ceph
#  group:
#    name: 'ceph'

#- name: create user ceph
#  user:
#    name: 'ceph'
#---------------------------------------
#end remove
